# Generated by Django 5.0.4 on 2024-05-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_onetimecode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
