# Generated by Django 5.0.4 on 2024-05-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_onetimecode_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetimecode',
            old_name='created_at',
            new_name='created',
        ),
    ]
