# Generated by Django 5.0.4 on 2024-05-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='agree',
            field=models.BooleanField(default=False),
        ),
    ]
